apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test
  name: operator-blueprint
  labels:
    app: operator-blueprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator-blueprint
  template:
    metadata:
      labels:
        app: operator-blueprint
    spec:
      containers:
      - name: operator-blueprint
        image: ghcr.io/stackzoo/operator-blueprint:0.1.4
