name: CI

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'README.md'
      - 'images'
  pull_request:
    branches: [ "*" ]
    paths-ignore:
      - 'README.md'
      - 'images'

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.49.0
          only-new-issues: false